### ISSUE TITLE
Support TheMovieDB as an image source for Anime Series

### ISSUE THREAD

**Issue by ScottDennison** [Fribb/MyAnimeList.bundle#23] opened 2021-04-04 16:58 UTC
#22 mentions that a full re-think of how mappings are done, however this is for version 7.

For a version 6 minor release in the mean time, I'm wondering whether it would be worth making the small change to allow MyAnimeList.bundle to use TheMovieDB as a image source for TV (anime series) entries.

Given the TheMovieDB API (at least the bits that are used) are 99% identical for Movie and TV calls (the only change I could see is the word "movie" being replaced with "tv" in the API url), it would not seem to take much code to do, unlike the changes required by #22.

I'm willing to code such a change and create a pull request, but wanted to get goahead before I made such a change.

**Comment by Fribb** [comment] 2021-04-04 18:06
I'm currently planning and organizing and thinking about how this all will look like, what makes sense and what doesn't etc.

There are quite a few things that have to be addressed in all of that.

The Metadata source for the Agent: This is bugging me for a while now. I want to retire the Atarashii API with v7.0.0 because it isn't maintained for a while now and I want to move to a new API, jikan, to be more up-to-date and don't have to dig into the API every time MAL changes something.

Image providers: this will not change really, I still want to support TheTVDB and TheMovieDB as integrated image providers. With the change to a paid API access with TheTVDB and TheMovieDB also providing metadata for TV-Show it is really a no brainer to make this also available on the TV-Show side **especially** since you can actually search with the TheTVDB ID on the TheMovieDB API and get results.

Mapping source: With the change from atarashii to jikan, the mapping generator would also have to be changed to compensate for the different responses between those APIs. But the issue is that I don't really want to spend much or rather any time with the generator at all anymore. With the projects mentioned in #22, there are projects to get those mappings in a much more reliable way than my generator could or would. They also run more frequently, I think every week instead of twice a month with my generator.

I don't think I will fully integrate that mapping into the Agent because this will bloat the agent up considerably and unnecessarily. Not to mention that the anime-list is also used by the Plex Meta Manager project. It would make more sense to keep the project as is, maybe slim it down considerably by removing the 1000 segments for the titles and the mapping and just have the full list in the format that already exists. The other projects would then be the source for those mappings between MAL -> AniDB -> TheTVDB. It could also be easier expanded by different IDs if there is some need for it.

That means that this feature will definitely come, just with the v7.0.0 because there are so many changes that I want to do that I don't think that the agent will still be the same anymore. On the other hand, as long as the TheTVDB APIv3 is still working there is really no rush in adding this to the agent, unless I have missed something.

**Comment by ScottDennison** [comment] 2021-04-04 19:55
This project (indirectly) is currently my only usage of TheTVDB, and I thought (incorrectly) that the retiration of the V3 API had already happened, and the next time I added a new show the plugin might throw some nasty errors. Luckily, that isn't the case.

**However**, I've done a search to try and find out a date for whne TheTVDB will shut down their V3 API.
Mostly places I have found didn't list a date, but two (https://community.synology.com/enu/forum/1/post/141423 and https://forums.sagetv.com/forums/showthread.php?t=66581) do - both saying March 2021, meaning the shut own of V3 might be imminent.
As such, it might not be possible to wait for v7.0.0 for such a change.

**Comment by Fribb** [comment] 2021-04-05 04:49
hmm, looks like it is imminent.

Okay, if you are willing you have my "go-ahead". As I mentioned, you wouldn't need to add a totally different mapping ID and request that but rather just use the TheTVDB ID from the mapping list and query the TheMovieDB API on the "tv" side. The TheMovieDB API says that this works [here](https://developers.themoviedb.org/3/find/find-by-id), something to definitely check out.

Or maybe you disable the TheTVDB entirely since, without v4 support, it wouldn't be able to do anything anyway. This would also only mean an update to the agent instead of also set some options for the user. With v7.0.0 this would then be a selection in the agent settings where you want to get the images from.

**Comment by Fribb** [comment] 2021-04-05 12:15
So it seems that the API deprecation got postponed according to the Quote here ZeroQI/Hama.bundle#457 to October 2021. So Enough time to get v7.0.0 on the road.

**Closed** 2021-09-05 10:15 UTC
Labels: enhancement
