### ISSUE TITLE
v7.1.0 Not working properly

### ISSUE THREAD

**Issue by andrew-stclair** [Fribb/MyAnimeList.bundle#36] opened 2022-05-02 13:24 UTC
When trying to setup a new library using version 7.1.0, i get the following errors

![image](https://user-images.githubusercontent.com/4944499/166240819-18433f88-e5ab-435e-8810-120177b5523a.png)

Using version 7.0.3 does not have this issue and works just fine

The URL both sides of those errors:
`Request: [10.0.0.23:54722 (Allowed Network (WAN))] POST /library/sections?name=Anime&type=show&agent=net.fribbtastic.coding.plex.myanimelist&scanner=BABS&language=en&importFromiTunes=&enableAutoPhotoTags=&downloadMedia=&location=%2FMedia%2FAnime (14 live) GZIP Signed-in Token (St0ner1995) (Firefox)`

**Comment by Fribb** [comment] 2022-05-02 14:07
I expanded the Language settings in the agent, but this shouldn't affect this to such a degree.

Can you provide more information about your setup? What OS do you use? Do you get a language selection next to the Title of the library when you want to create it? If you use a Linux OS, or something like that, are the permissions and ownership set correctly? Please provide the Agent logs as well.

**Comment by Fribb** [comment] 2022-05-11 08:37
Is this still an issue or can I close this?

**Closed** 2022-05-19 04:04 UTC

**Comment by Fribb** [comment] 2022-05-19 04:15
How did you resolve the issue?

**Comment by andrew-stclair** [comment] 2022-05-19 07:40
To be honest, i keep forgetting to check if the latest version works. So i closed the ticket. When i remember to check, I'll reopen the ticket if it's still an issue or just comment if it's fixed

Sorry about that

**Comment by notAutomne** [comment] 2023-04-02 01:14
Same issue: ![](https://upload.illya.network/EUVzZc28HuDNuHBCl2NbvtaV)

**Comment by notAutomne** [comment] 2023-04-02 01:19
root cause found : i must set English and not French
![](https://upload.illya.network/jQqUwX0SC7SGqdT7QqEDQPXt/direct)

**Comment by Fribb** [comment] 2023-04-02 04:18
I just tried it with my test instance and set the language to French and could create libraries without issues.

Can you provide more information so that I can try to replicate the issue?

* Are you running the latest version?
* What language is your Plex instance set to?
* What type of library are you trying to create?
* what language do you try to set there?

On a side note, the library language isn't considered by the agent so you could just set it to English to circumvent the issue.

Keep in mind that French itself is only supported for the Staff language, the Title language is currently only for Japanese and English (and default).

**Comment by notAutomne** [comment] 2023-04-03 08:55
Hello,

I was migrating a library from Hama.bundle to MAL.bundle.

Runing the latest PMS (1.31) on Archlinux (AUR package).

TV Show library that was previously set in Hama.bundle + AAS in French.

I just changed the agent from Hama to MAL.


De : Fribb ***@***.***>
Envoyé : dimanche 2 avril 2023 06:18
À : Fribb/MyAnimeList.bundle ***@***.***>
Cc : Marwan ***@***.***>; Comment ***@***.***>
Objet : Re: [Fribb/MyAnimeList.bundle] v7.1.0 Not working properly (Issue #36)


I just tried it with my test instance and set the language to French and could create libraries without issues.

Can you provide more information so that I can try to replicate the issue?

  *   Are you running the latest version?
  *   What language is your Plex instance set to?
  *   What type of library are you trying to create?
  *   what language do you try to set there?

On a side note, the library language isn't considered by the agent so you could just set it to English to circumvent the issue.

Keep in mind that French itself is only supported for the Staff language, the Title language is currently only for Japanese and English (and default).

**Comment by Fribb** [comment] 2023-04-03 09:23
Since you would get a whole new set of Metadata through the MyAnimeList Metadata Agent I would first recommend you use a new library for it instead of switching the Metadata Agent and see if that helps.
